// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/job/job.proto

package jobpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	TgUsername    string                 `protobuf:"bytes,5,opt,name=tg_username,json=tgUsername,proto3" json:"tg_username,omitempty"`
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Sections      []*SectionAnswer       `protobuf:"bytes,7,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTestRequest) Reset() {
	*x = SubmitTestRequest{}
	mi := &file_proto_job_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTestRequest) ProtoMessage() {}

func (x *SubmitTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTestRequest.ProtoReflect.Descriptor instead.
func (*SubmitTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTestRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SubmitTestRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SubmitTestRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SubmitTestRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubmitTestRequest) GetTgUsername() string {
	if x != nil {
		return x.TgUsername
	}
	return ""
}

func (x *SubmitTestRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SubmitTestRequest) GetSections() []*SectionAnswer {
	if x != nil {
		return x.Sections
	}
	return nil
}

type SectionAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     uint64                 `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Questions     []*QuestionAnswer      `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionAnswer) Reset() {
	*x = SectionAnswer{}
	mi := &file_proto_job_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionAnswer) ProtoMessage() {}

func (x *SectionAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionAnswer.ProtoReflect.Descriptor instead.
func (*SectionAnswer) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{1}
}

func (x *SectionAnswer) GetSectionId() uint64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *SectionAnswer) GetQuestions() []*QuestionAnswer {
	if x != nil {
		return x.Questions
	}
	return nil
}

type QuestionAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    uint64                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	OptionIds     []uint64               `protobuf:"varint,2,rep,packed,name=option_ids,json=optionIds,proto3" json:"option_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionAnswer) Reset() {
	*x = QuestionAnswer{}
	mi := &file_proto_job_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionAnswer) ProtoMessage() {}

func (x *QuestionAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionAnswer.ProtoReflect.Descriptor instead.
func (*QuestionAnswer) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{2}
}

func (x *QuestionAnswer) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *QuestionAnswer) GetOptionIds() []uint64 {
	if x != nil {
		return x.OptionIds
	}
	return nil
}

type SubmitTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTestResponse) Reset() {
	*x = SubmitTestResponse{}
	mi := &file_proto_job_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTestResponse) ProtoMessage() {}

func (x *SubmitTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTestResponse.ProtoReflect.Descriptor instead.
func (*SubmitTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_job_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitTestResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_proto_job_job_proto protoreflect.FileDescriptor

const file_proto_job_job_proto_rawDesc = "" +
	"\n" +
	"\x13proto/job/job.proto\x12\x03job\"\xde\x01\n" +
	"\x11SubmitTestRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1f\n" +
	"\vtg_username\x18\x05 \x01(\tR\n" +
	"tgUsername\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12.\n" +
	"\bsections\x18\a \x03(\v2\x12.job.SectionAnswerR\bsections\"a\n" +
	"\rSectionAnswer\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x04R\tsectionId\x121\n" +
	"\tquestions\x18\x02 \x03(\v2\x13.job.QuestionAnswerR\tquestions\"P\n" +
	"\x0eQuestionAnswer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\x12\x1d\n" +
	"\n" +
	"option_ids\x18\x02 \x03(\x04R\toptionIds\"X\n" +
	"\x12SubmitTestResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key2K\n" +
	"\n" +
	"JobService\x12=\n" +
	"\n" +
	"SubmitTest\x12\x16.job.SubmitTestRequest\x1a\x17.job.SubmitTestResponseB.Z,github.com/khbdev/grps-proto/proto/job;jobpbb\x06proto3"

var (
	file_proto_job_job_proto_rawDescOnce sync.Once
	file_proto_job_job_proto_rawDescData []byte
)

func file_proto_job_job_proto_rawDescGZIP() []byte {
	file_proto_job_job_proto_rawDescOnce.Do(func() {
		file_proto_job_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_job_job_proto_rawDesc), len(file_proto_job_job_proto_rawDesc)))
	})
	return file_proto_job_job_proto_rawDescData
}

var file_proto_job_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_job_job_proto_goTypes = []any{
	(*SubmitTestRequest)(nil),  // 0: job.SubmitTestRequest
	(*SectionAnswer)(nil),      // 1: job.SectionAnswer
	(*QuestionAnswer)(nil),     // 2: job.QuestionAnswer
	(*SubmitTestResponse)(nil), // 3: job.SubmitTestResponse
}
var file_proto_job_job_proto_depIdxs = []int32{
	1, // 0: job.SubmitTestRequest.sections:type_name -> job.SectionAnswer
	2, // 1: job.SectionAnswer.questions:type_name -> job.QuestionAnswer
	0, // 2: job.JobService.SubmitTest:input_type -> job.SubmitTestRequest
	3, // 3: job.JobService.SubmitTest:output_type -> job.SubmitTestResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_job_job_proto_init() }
func file_proto_job_job_proto_init() {
	if File_proto_job_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_job_job_proto_rawDesc), len(file_proto_job_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_job_job_proto_goTypes,
		DependencyIndexes: file_proto_job_job_proto_depIdxs,
		MessageInfos:      file_proto_job_job_proto_msgTypes,
	}.Build()
	File_proto_job_job_proto = out.File
	file_proto_job_job_proto_goTypes = nil
	file_proto_job_job_proto_depIdxs = nil
}
