syntax = "proto3";

package exam;

option go_package = "github.com/khbdev/proto-online-test/proto/exam;exampb";

// Exam message
message Exam {
  uint64 id = 1; // DB-generated ID, response’da bo‘ladi
  string title = 2;
  string description = 3;
  repeated uint64 section_ids = 4;
}

// Create Exam
message CreateExamRequest {
  string title = 1;
  string description = 2;
  repeated uint64 section_ids = 3;
}

message CreateExamResponse {
  Exam exam = 1;
}

// Get Exam List
message GetExamListRequest {}

message GetExamListResponse {
  repeated Exam exams = 1;
}

// Get Exam by ID
message GetExamByIDRequest {
  uint64 id = 1; // ID orqali olish
}

message GetExamByIDResponse {
  Exam exam = 1;
}

// Update Exam
message UpdateExamRequest {
  uint64 id = 1; // DB ID bo‘yicha update qilish
  string title = 2;
  string description = 3;
  repeated uint64 section_ids = 4;
}

message UpdateExamResponse {
  Exam exam = 1;
}

// Delete Exam
message DeleteExamRequest {
  uint64 id = 1; // DB ID bo‘yicha o‘chirish
}

message DeleteExamResponse {
  bool success = 1;
}

// ExamService gRPC service
service ExamService {
  rpc CreateExam(CreateExamRequest) returns (CreateExamResponse);
  rpc GetExamList(GetExamListRequest) returns (GetExamListResponse);
  rpc GetExamByID(GetExamByIDRequest) returns (GetExamByIDResponse);
  rpc UpdateExam(UpdateExamRequest) returns (UpdateExamResponse);
  rpc DeleteExam(DeleteExamRequest) returns (DeleteExamResponse);
}
