syntax = "proto3";

package exam;

option go_package = "github.com/khbdev/proto-online-test/proto/exam;exampb";

message Exam {
  uint64 id = 1;
  string title = 2;
  string description = 3;
  repeated uint64 section_ids = 4; 
}

message CreateExamRequest {
  string title = 1;
  string description = 2;
  repeated uint64 section_ids = 3;
}

message CreateExamResponse {
  Exam exam = 1;
}

message GetExamListRequest {}

message GetExamListResponse {
  repeated Exam exams = 1;
}

message GetExamByIDRequest {
  uint64 id = 1;
}

message GetExamByIDResponse {
  Exam exam = 1;
}

message UpdateExamRequest {
  uint64 id = 1;
  string title = 2;
  string description = 3;
  repeated uint64 section_ids = 4;
}

message UpdateExamResponse {
  Exam exam = 1;
}

message DeleteExamRequest {
  uint64 id = 1;
}

message DeleteExamResponse {
  bool success = 1;
}

service ExamService {
  rpc CreateExam(CreateExamRequest) returns (CreateExamResponse);
  rpc GetExamList(GetExamListRequest) returns (GetExamListResponse);
  rpc GetExamByID(GetExamByIDRequest) returns (GetExamByIDResponse);
  rpc UpdateExam(UpdateExamRequest) returns (UpdateExamResponse);
  rpc DeleteExam(DeleteExamRequest) returns (DeleteExamResponse);
}
