// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/exam/exam.proto

package exampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Exam message
type Exam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SectionIds    []uint64               `protobuf:"varint,4,rep,packed,name=section_ids,json=sectionIds,proto3" json:"section_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exam) Reset() {
	*x = Exam{}
	mi := &file_proto_exam_exam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exam) ProtoMessage() {}

func (x *Exam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exam.ProtoReflect.Descriptor instead.
func (*Exam) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{0}
}

func (x *Exam) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exam) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Exam) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Exam) GetSectionIds() []uint64 {
	if x != nil {
		return x.SectionIds
	}
	return nil
}

// Create Exam
type CreateExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SectionIds    []uint64               `protobuf:"varint,3,rep,packed,name=section_ids,json=sectionIds,proto3" json:"section_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExamRequest) Reset() {
	*x = CreateExamRequest{}
	mi := &file_proto_exam_exam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExamRequest) ProtoMessage() {}

func (x *CreateExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExamRequest.ProtoReflect.Descriptor instead.
func (*CreateExamRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExamRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateExamRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateExamRequest) GetSectionIds() []uint64 {
	if x != nil {
		return x.SectionIds
	}
	return nil
}

type CreateExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exam          *Exam                  `protobuf:"bytes,1,opt,name=exam,proto3" json:"exam,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExamResponse) Reset() {
	*x = CreateExamResponse{}
	mi := &file_proto_exam_exam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExamResponse) ProtoMessage() {}

func (x *CreateExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExamResponse.ProtoReflect.Descriptor instead.
func (*CreateExamResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{2}
}

func (x *CreateExamResponse) GetExam() *Exam {
	if x != nil {
		return x.Exam
	}
	return nil
}

// Get Exam List
type GetExamListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamListRequest) Reset() {
	*x = GetExamListRequest{}
	mi := &file_proto_exam_exam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamListRequest) ProtoMessage() {}

func (x *GetExamListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamListRequest.ProtoReflect.Descriptor instead.
func (*GetExamListRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{3}
}

type GetExamListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exams         []*Exam                `protobuf:"bytes,1,rep,name=exams,proto3" json:"exams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamListResponse) Reset() {
	*x = GetExamListResponse{}
	mi := &file_proto_exam_exam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamListResponse) ProtoMessage() {}

func (x *GetExamListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamListResponse.ProtoReflect.Descriptor instead.
func (*GetExamListResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{4}
}

func (x *GetExamListResponse) GetExams() []*Exam {
	if x != nil {
		return x.Exams
	}
	return nil
}

// Get Exam by ID
type GetExamByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamByIDRequest) Reset() {
	*x = GetExamByIDRequest{}
	mi := &file_proto_exam_exam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamByIDRequest) ProtoMessage() {}

func (x *GetExamByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamByIDRequest.ProtoReflect.Descriptor instead.
func (*GetExamByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{5}
}

func (x *GetExamByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetExamByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exam          *Exam                  `protobuf:"bytes,1,opt,name=exam,proto3" json:"exam,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamByIDResponse) Reset() {
	*x = GetExamByIDResponse{}
	mi := &file_proto_exam_exam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamByIDResponse) ProtoMessage() {}

func (x *GetExamByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamByIDResponse.ProtoReflect.Descriptor instead.
func (*GetExamByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{6}
}

func (x *GetExamByIDResponse) GetExam() *Exam {
	if x != nil {
		return x.Exam
	}
	return nil
}

// Update Exam
type UpdateExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SectionIds    []uint64               `protobuf:"varint,4,rep,packed,name=section_ids,json=sectionIds,proto3" json:"section_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExamRequest) Reset() {
	*x = UpdateExamRequest{}
	mi := &file_proto_exam_exam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExamRequest) ProtoMessage() {}

func (x *UpdateExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExamRequest.ProtoReflect.Descriptor instead.
func (*UpdateExamRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateExamRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateExamRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateExamRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateExamRequest) GetSectionIds() []uint64 {
	if x != nil {
		return x.SectionIds
	}
	return nil
}

type UpdateExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exam          *Exam                  `protobuf:"bytes,1,opt,name=exam,proto3" json:"exam,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExamResponse) Reset() {
	*x = UpdateExamResponse{}
	mi := &file_proto_exam_exam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExamResponse) ProtoMessage() {}

func (x *UpdateExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExamResponse.ProtoReflect.Descriptor instead.
func (*UpdateExamResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateExamResponse) GetExam() *Exam {
	if x != nil {
		return x.Exam
	}
	return nil
}

// Delete Exam
type DeleteExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExamRequest) Reset() {
	*x = DeleteExamRequest{}
	mi := &file_proto_exam_exam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExamRequest) ProtoMessage() {}

func (x *DeleteExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExamRequest.ProtoReflect.Descriptor instead.
func (*DeleteExamRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteExamRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExamResponse) Reset() {
	*x = DeleteExamResponse{}
	mi := &file_proto_exam_exam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExamResponse) ProtoMessage() {}

func (x *DeleteExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExamResponse.ProtoReflect.Descriptor instead.
func (*DeleteExamResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteExamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_exam_exam_proto protoreflect.FileDescriptor

const file_proto_exam_exam_proto_rawDesc = "" +
	"\n" +
	"\x15proto/exam/exam.proto\x12\x04exam\"o\n" +
	"\x04Exam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vsection_ids\x18\x04 \x03(\x04R\n" +
	"sectionIds\"l\n" +
	"\x11CreateExamRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vsection_ids\x18\x03 \x03(\x04R\n" +
	"sectionIds\"4\n" +
	"\x12CreateExamResponse\x12\x1e\n" +
	"\x04exam\x18\x01 \x01(\v2\n" +
	".exam.ExamR\x04exam\"\x14\n" +
	"\x12GetExamListRequest\"7\n" +
	"\x13GetExamListResponse\x12 \n" +
	"\x05exams\x18\x01 \x03(\v2\n" +
	".exam.ExamR\x05exams\"$\n" +
	"\x12GetExamByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"5\n" +
	"\x13GetExamByIDResponse\x12\x1e\n" +
	"\x04exam\x18\x01 \x01(\v2\n" +
	".exam.ExamR\x04exam\"|\n" +
	"\x11UpdateExamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vsection_ids\x18\x04 \x03(\x04R\n" +
	"sectionIds\"4\n" +
	"\x12UpdateExamResponse\x12\x1e\n" +
	"\x04exam\x18\x01 \x01(\v2\n" +
	".exam.ExamR\x04exam\"#\n" +
	"\x11DeleteExamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\".\n" +
	"\x12DeleteExamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd8\x02\n" +
	"\vExamService\x12?\n" +
	"\n" +
	"CreateExam\x12\x17.exam.CreateExamRequest\x1a\x18.exam.CreateExamResponse\x12B\n" +
	"\vGetExamList\x12\x18.exam.GetExamListRequest\x1a\x19.exam.GetExamListResponse\x12B\n" +
	"\vGetExamByID\x12\x18.exam.GetExamByIDRequest\x1a\x19.exam.GetExamByIDResponse\x12?\n" +
	"\n" +
	"UpdateExam\x12\x17.exam.UpdateExamRequest\x1a\x18.exam.UpdateExamResponse\x12?\n" +
	"\n" +
	"DeleteExam\x12\x17.exam.DeleteExamRequest\x1a\x18.exam.DeleteExamResponseB7Z5github.com/khbdev/proto-online-test/proto/exam;exampbb\x06proto3"

var (
	file_proto_exam_exam_proto_rawDescOnce sync.Once
	file_proto_exam_exam_proto_rawDescData []byte
)

func file_proto_exam_exam_proto_rawDescGZIP() []byte {
	file_proto_exam_exam_proto_rawDescOnce.Do(func() {
		file_proto_exam_exam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exam_exam_proto_rawDesc), len(file_proto_exam_exam_proto_rawDesc)))
	})
	return file_proto_exam_exam_proto_rawDescData
}

var file_proto_exam_exam_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_exam_exam_proto_goTypes = []any{
	(*Exam)(nil),                // 0: exam.Exam
	(*CreateExamRequest)(nil),   // 1: exam.CreateExamRequest
	(*CreateExamResponse)(nil),  // 2: exam.CreateExamResponse
	(*GetExamListRequest)(nil),  // 3: exam.GetExamListRequest
	(*GetExamListResponse)(nil), // 4: exam.GetExamListResponse
	(*GetExamByIDRequest)(nil),  // 5: exam.GetExamByIDRequest
	(*GetExamByIDResponse)(nil), // 6: exam.GetExamByIDResponse
	(*UpdateExamRequest)(nil),   // 7: exam.UpdateExamRequest
	(*UpdateExamResponse)(nil),  // 8: exam.UpdateExamResponse
	(*DeleteExamRequest)(nil),   // 9: exam.DeleteExamRequest
	(*DeleteExamResponse)(nil),  // 10: exam.DeleteExamResponse
}
var file_proto_exam_exam_proto_depIdxs = []int32{
	0,  // 0: exam.CreateExamResponse.exam:type_name -> exam.Exam
	0,  // 1: exam.GetExamListResponse.exams:type_name -> exam.Exam
	0,  // 2: exam.GetExamByIDResponse.exam:type_name -> exam.Exam
	0,  // 3: exam.UpdateExamResponse.exam:type_name -> exam.Exam
	1,  // 4: exam.ExamService.CreateExam:input_type -> exam.CreateExamRequest
	3,  // 5: exam.ExamService.GetExamList:input_type -> exam.GetExamListRequest
	5,  // 6: exam.ExamService.GetExamByID:input_type -> exam.GetExamByIDRequest
	7,  // 7: exam.ExamService.UpdateExam:input_type -> exam.UpdateExamRequest
	9,  // 8: exam.ExamService.DeleteExam:input_type -> exam.DeleteExamRequest
	2,  // 9: exam.ExamService.CreateExam:output_type -> exam.CreateExamResponse
	4,  // 10: exam.ExamService.GetExamList:output_type -> exam.GetExamListResponse
	6,  // 11: exam.ExamService.GetExamByID:output_type -> exam.GetExamByIDResponse
	8,  // 12: exam.ExamService.UpdateExam:output_type -> exam.UpdateExamResponse
	10, // 13: exam.ExamService.DeleteExam:output_type -> exam.DeleteExamResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_exam_exam_proto_init() }
func file_proto_exam_exam_proto_init() {
	if File_proto_exam_exam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exam_exam_proto_rawDesc), len(file_proto_exam_exam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exam_exam_proto_goTypes,
		DependencyIndexes: file_proto_exam_exam_proto_depIdxs,
		MessageInfos:      file_proto_exam_exam_proto_msgTypes,
	}.Build()
	File_proto_exam_exam_proto = out.File
	file_proto_exam_exam_proto_goTypes = nil
	file_proto_exam_exam_proto_depIdxs = nil
}
