// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/exam/exam.proto

package exampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SectionIds    []uint64               `protobuf:"varint,4,rep,packed,name=section_ids,json=sectionIds,proto3" json:"section_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_exam_exam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Content) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Content) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Content) GetSectionIds() []uint64 {
	if x != nil {
		return x.SectionIds
	}
	return nil
}

type CreateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SectionIds    []uint64               `protobuf:"varint,3,rep,packed,name=section_ids,json=sectionIds,proto3" json:"section_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentRequest) Reset() {
	*x = CreateContentRequest{}
	mi := &file_proto_exam_exam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRequest) ProtoMessage() {}

func (x *CreateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRequest.ProtoReflect.Descriptor instead.
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateContentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateContentRequest) GetSectionIds() []uint64 {
	if x != nil {
		return x.SectionIds
	}
	return nil
}

type CreateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentResponse) Reset() {
	*x = CreateContentResponse{}
	mi := &file_proto_exam_exam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentResponse) ProtoMessage() {}

func (x *CreateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentResponse.ProtoReflect.Descriptor instead.
func (*CreateContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{2}
}

func (x *CreateContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetContentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentListRequest) Reset() {
	*x = GetContentListRequest{}
	mi := &file_proto_exam_exam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentListRequest) ProtoMessage() {}

func (x *GetContentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentListRequest.ProtoReflect.Descriptor instead.
func (*GetContentListRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{3}
}

type GetContentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*Content             `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentListResponse) Reset() {
	*x = GetContentListResponse{}
	mi := &file_proto_exam_exam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentListResponse) ProtoMessage() {}

func (x *GetContentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentListResponse.ProtoReflect.Descriptor instead.
func (*GetContentListResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{4}
}

func (x *GetContentListResponse) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

type GetContentByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentByIDRequest) Reset() {
	*x = GetContentByIDRequest{}
	mi := &file_proto_exam_exam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentByIDRequest) ProtoMessage() {}

func (x *GetContentByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentByIDRequest.ProtoReflect.Descriptor instead.
func (*GetContentByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{5}
}

func (x *GetContentByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetContentByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentByIDResponse) Reset() {
	*x = GetContentByIDResponse{}
	mi := &file_proto_exam_exam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentByIDResponse) ProtoMessage() {}

func (x *GetContentByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentByIDResponse.ProtoReflect.Descriptor instead.
func (*GetContentByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{6}
}

func (x *GetContentByIDResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type UpdateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SectionIds    []uint64               `protobuf:"varint,4,rep,packed,name=section_ids,json=sectionIds,proto3" json:"section_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContentRequest) Reset() {
	*x = UpdateContentRequest{}
	mi := &file_proto_exam_exam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentRequest) ProtoMessage() {}

func (x *UpdateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentRequest.ProtoReflect.Descriptor instead.
func (*UpdateContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateContentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateContentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateContentRequest) GetSectionIds() []uint64 {
	if x != nil {
		return x.SectionIds
	}
	return nil
}

type UpdateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContentResponse) Reset() {
	*x = UpdateContentResponse{}
	mi := &file_proto_exam_exam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentResponse) ProtoMessage() {}

func (x *UpdateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentResponse.ProtoReflect.Descriptor instead.
func (*UpdateContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type DeleteContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentRequest) Reset() {
	*x = DeleteContentRequest{}
	mi := &file_proto_exam_exam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentRequest) ProtoMessage() {}

func (x *DeleteContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentRequest.ProtoReflect.Descriptor instead.
func (*DeleteContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteContentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentResponse) Reset() {
	*x = DeleteContentResponse{}
	mi := &file_proto_exam_exam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentResponse) ProtoMessage() {}

func (x *DeleteContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_exam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentResponse.ProtoReflect.Descriptor instead.
func (*DeleteContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_exam_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteContentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_exam_exam_proto protoreflect.FileDescriptor

const file_proto_exam_exam_proto_rawDesc = "" +
	"\n" +
	"\x15proto/exam/exam.proto\x12\x04exam\"r\n" +
	"\aContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vsection_ids\x18\x04 \x03(\x04R\n" +
	"sectionIds\"o\n" +
	"\x14CreateContentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vsection_ids\x18\x03 \x03(\x04R\n" +
	"sectionIds\"@\n" +
	"\x15CreateContentResponse\x12'\n" +
	"\acontent\x18\x01 \x01(\v2\r.exam.ContentR\acontent\"\x17\n" +
	"\x15GetContentListRequest\"C\n" +
	"\x16GetContentListResponse\x12)\n" +
	"\bcontents\x18\x01 \x03(\v2\r.exam.ContentR\bcontents\"'\n" +
	"\x15GetContentByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"A\n" +
	"\x16GetContentByIDResponse\x12'\n" +
	"\acontent\x18\x01 \x01(\v2\r.exam.ContentR\acontent\"\x7f\n" +
	"\x14UpdateContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vsection_ids\x18\x04 \x03(\x04R\n" +
	"sectionIds\"@\n" +
	"\x15UpdateContentResponse\x12'\n" +
	"\acontent\x18\x01 \x01(\v2\r.exam.ContentR\acontent\"&\n" +
	"\x14DeleteContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"1\n" +
	"\x15DeleteContentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x88\x03\n" +
	"\x0eContentService\x12H\n" +
	"\rCreateContent\x12\x1a.exam.CreateContentRequest\x1a\x1b.exam.CreateContentResponse\x12K\n" +
	"\x0eGetContentList\x12\x1b.exam.GetContentListRequest\x1a\x1c.exam.GetContentListResponse\x12K\n" +
	"\x0eGetContentByID\x12\x1b.exam.GetContentByIDRequest\x1a\x1c.exam.GetContentByIDResponse\x12H\n" +
	"\rUpdateContent\x12\x1a.exam.UpdateContentRequest\x1a\x1b.exam.UpdateContentResponse\x12H\n" +
	"\rDeleteContent\x12\x1a.exam.DeleteContentRequest\x1a\x1b.exam.DeleteContentResponseB7Z5github.com/khbdev/proto-online-test/proto/exam;exampbb\x06proto3"

var (
	file_proto_exam_exam_proto_rawDescOnce sync.Once
	file_proto_exam_exam_proto_rawDescData []byte
)

func file_proto_exam_exam_proto_rawDescGZIP() []byte {
	file_proto_exam_exam_proto_rawDescOnce.Do(func() {
		file_proto_exam_exam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exam_exam_proto_rawDesc), len(file_proto_exam_exam_proto_rawDesc)))
	})
	return file_proto_exam_exam_proto_rawDescData
}

var file_proto_exam_exam_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_exam_exam_proto_goTypes = []any{
	(*Content)(nil),                // 0: exam.Content
	(*CreateContentRequest)(nil),   // 1: exam.CreateContentRequest
	(*CreateContentResponse)(nil),  // 2: exam.CreateContentResponse
	(*GetContentListRequest)(nil),  // 3: exam.GetContentListRequest
	(*GetContentListResponse)(nil), // 4: exam.GetContentListResponse
	(*GetContentByIDRequest)(nil),  // 5: exam.GetContentByIDRequest
	(*GetContentByIDResponse)(nil), // 6: exam.GetContentByIDResponse
	(*UpdateContentRequest)(nil),   // 7: exam.UpdateContentRequest
	(*UpdateContentResponse)(nil),  // 8: exam.UpdateContentResponse
	(*DeleteContentRequest)(nil),   // 9: exam.DeleteContentRequest
	(*DeleteContentResponse)(nil),  // 10: exam.DeleteContentResponse
}
var file_proto_exam_exam_proto_depIdxs = []int32{
	0,  // 0: exam.CreateContentResponse.content:type_name -> exam.Content
	0,  // 1: exam.GetContentListResponse.contents:type_name -> exam.Content
	0,  // 2: exam.GetContentByIDResponse.content:type_name -> exam.Content
	0,  // 3: exam.UpdateContentResponse.content:type_name -> exam.Content
	1,  // 4: exam.ContentService.CreateContent:input_type -> exam.CreateContentRequest
	3,  // 5: exam.ContentService.GetContentList:input_type -> exam.GetContentListRequest
	5,  // 6: exam.ContentService.GetContentByID:input_type -> exam.GetContentByIDRequest
	7,  // 7: exam.ContentService.UpdateContent:input_type -> exam.UpdateContentRequest
	9,  // 8: exam.ContentService.DeleteContent:input_type -> exam.DeleteContentRequest
	2,  // 9: exam.ContentService.CreateContent:output_type -> exam.CreateContentResponse
	4,  // 10: exam.ContentService.GetContentList:output_type -> exam.GetContentListResponse
	6,  // 11: exam.ContentService.GetContentByID:output_type -> exam.GetContentByIDResponse
	8,  // 12: exam.ContentService.UpdateContent:output_type -> exam.UpdateContentResponse
	10, // 13: exam.ContentService.DeleteContent:output_type -> exam.DeleteContentResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_exam_exam_proto_init() }
func file_proto_exam_exam_proto_init() {
	if File_proto_exam_exam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exam_exam_proto_rawDesc), len(file_proto_exam_exam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exam_exam_proto_goTypes,
		DependencyIndexes: file_proto_exam_exam_proto_depIdxs,
		MessageInfos:      file_proto_exam_exam_proto_msgTypes,
	}.Build()
	File_proto_exam_exam_proto = out.File
	file_proto_exam_exam_proto_goTypes = nil
	file_proto_exam_exam_proto_depIdxs = nil
}
