// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/filter/filter.proto

package filterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Year          string                 `protobuf:"bytes,6,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_proto_filter_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filter_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_filter_filter_proto_rawDescGZIP(), []int{0}
}

func (x *FilterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *FilterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *FilterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *FilterRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_proto_filter_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filter_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_proto_filter_filter_proto_rawDescGZIP(), []int{1}
}

func (x *Section) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Section) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_filter_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filter_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_filter_filter_proto_rawDescGZIP(), []int{2}
}

func (x *Question) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionIds     []int64                `protobuf:"varint,1,rep,packed,name=option_ids,json=optionIds,proto3" json:"option_ids,omitempty"`
	QuestionId    int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_proto_filter_filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filter_filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_proto_filter_filter_proto_rawDescGZIP(), []int{3}
}

func (x *Answer) GetOptionIds() []int64 {
	if x != nil {
		return x.OptionIds
	}
	return nil
}

func (x *Answer) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type FilterUser struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       string                 `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	FirstName       string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName        string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone           string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Email           string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	TgUsername      string                 `protobuf:"bytes,9,opt,name=tg_username,json=tgUsername,proto3" json:"tg_username,omitempty"`
	Bolimlar        []*Section             `protobuf:"bytes,10,rep,name=bolimlar,proto3" json:"bolimlar,omitempty"`
	Savollar        []*Question            `protobuf:"bytes,11,rep,name=savollar,proto3" json:"savollar,omitempty"`
	Javoblar        []*Answer              `protobuf:"bytes,12,rep,name=javoblar,proto3" json:"javoblar,omitempty"`
	TogriJavoblar   int32                  `protobuf:"varint,13,opt,name=togri_javoblar,json=togriJavoblar,proto3" json:"togri_javoblar,omitempty"`
	NatogriJavoblar int32                  `protobuf:"varint,14,opt,name=natogri_javoblar,json=natogriJavoblar,proto3" json:"natogri_javoblar,omitempty"`
	ScorePercent    float64                `protobuf:"fixed64,15,opt,name=score_percent,json=scorePercent,proto3" json:"score_percent,omitempty"`
	Description     string                 `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FilterUser) Reset() {
	*x = FilterUser{}
	mi := &file_proto_filter_filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterUser) ProtoMessage() {}

func (x *FilterUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filter_filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterUser.ProtoReflect.Descriptor instead.
func (*FilterUser) Descriptor() ([]byte, []int) {
	return file_proto_filter_filter_proto_rawDescGZIP(), []int{4}
}

func (x *FilterUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FilterUser) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FilterUser) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *FilterUser) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *FilterUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *FilterUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *FilterUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *FilterUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FilterUser) GetTgUsername() string {
	if x != nil {
		return x.TgUsername
	}
	return ""
}

func (x *FilterUser) GetBolimlar() []*Section {
	if x != nil {
		return x.Bolimlar
	}
	return nil
}

func (x *FilterUser) GetSavollar() []*Question {
	if x != nil {
		return x.Savollar
	}
	return nil
}

func (x *FilterUser) GetJavoblar() []*Answer {
	if x != nil {
		return x.Javoblar
	}
	return nil
}

func (x *FilterUser) GetTogriJavoblar() int32 {
	if x != nil {
		return x.TogriJavoblar
	}
	return 0
}

func (x *FilterUser) GetNatogriJavoblar() int32 {
	if x != nil {
		return x.NatogriJavoblar
	}
	return 0
}

func (x *FilterUser) GetScorePercent() float64 {
	if x != nil {
		return x.ScorePercent
	}
	return 0
}

func (x *FilterUser) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*FilterUser          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // <-- User -> FilterUser
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_proto_filter_filter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filter_filter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_proto_filter_filter_proto_rawDescGZIP(), []int{5}
}

func (x *UserList) GetUsers() []*FilterUser {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_proto_filter_filter_proto protoreflect.FileDescriptor

const file_proto_filter_filter_proto_rawDesc = "" +
	"\n" +
	"\x19proto/filter/filter.proto\x12\x06filter\"u\n" +
	"\rFilterRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x12\n" +
	"\x04year\x18\x06 \x01(\tR\x04year\"-\n" +
	"\aSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\".\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"H\n" +
	"\x06Answer\x12\x1d\n" +
	"\n" +
	"option_ids\x18\x01 \x03(\x03R\toptionIds\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\"\xa2\x04\n" +
	"\n" +
	"FilterUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\tR\tdeletedAt\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x1f\n" +
	"\vtg_username\x18\t \x01(\tR\n" +
	"tgUsername\x12+\n" +
	"\bbolimlar\x18\n" +
	" \x03(\v2\x0f.filter.SectionR\bbolimlar\x12,\n" +
	"\bsavollar\x18\v \x03(\v2\x10.filter.QuestionR\bsavollar\x12*\n" +
	"\bjavoblar\x18\f \x03(\v2\x0e.filter.AnswerR\bjavoblar\x12%\n" +
	"\x0etogri_javoblar\x18\r \x01(\x05R\rtogriJavoblar\x12)\n" +
	"\x10natogri_javoblar\x18\x0e \x01(\x05R\x0fnatogriJavoblar\x12#\n" +
	"\rscore_percent\x18\x0f \x01(\x01R\fscorePercent\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\"4\n" +
	"\bUserList\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.filter.FilterUserR\x05users2B\n" +
	"\vUserService\x123\n" +
	"\bGetUsers\x12\x15.filter.FilterRequest\x1a\x10.filter.UserListB;Z9github.com/khbdev/proto-online-test/proto/filter;filterpbb\x06proto3"

var (
	file_proto_filter_filter_proto_rawDescOnce sync.Once
	file_proto_filter_filter_proto_rawDescData []byte
)

func file_proto_filter_filter_proto_rawDescGZIP() []byte {
	file_proto_filter_filter_proto_rawDescOnce.Do(func() {
		file_proto_filter_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_filter_filter_proto_rawDesc), len(file_proto_filter_filter_proto_rawDesc)))
	})
	return file_proto_filter_filter_proto_rawDescData
}

var file_proto_filter_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_filter_filter_proto_goTypes = []any{
	(*FilterRequest)(nil), // 0: filter.FilterRequest
	(*Section)(nil),       // 1: filter.Section
	(*Question)(nil),      // 2: filter.Question
	(*Answer)(nil),        // 3: filter.Answer
	(*FilterUser)(nil),    // 4: filter.FilterUser
	(*UserList)(nil),      // 5: filter.UserList
}
var file_proto_filter_filter_proto_depIdxs = []int32{
	1, // 0: filter.FilterUser.bolimlar:type_name -> filter.Section
	2, // 1: filter.FilterUser.savollar:type_name -> filter.Question
	3, // 2: filter.FilterUser.javoblar:type_name -> filter.Answer
	4, // 3: filter.UserList.users:type_name -> filter.FilterUser
	0, // 4: filter.UserService.GetUsers:input_type -> filter.FilterRequest
	5, // 5: filter.UserService.GetUsers:output_type -> filter.UserList
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_filter_filter_proto_init() }
func file_proto_filter_filter_proto_init() {
	if File_proto_filter_filter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_filter_filter_proto_rawDesc), len(file_proto_filter_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_filter_filter_proto_goTypes,
		DependencyIndexes: file_proto_filter_filter_proto_depIdxs,
		MessageInfos:      file_proto_filter_filter_proto_msgTypes,
	}.Build()
	File_proto_filter_filter_proto = out.File
	file_proto_filter_filter_proto_goTypes = nil
	file_proto_filter_filter_proto_depIdxs = nil
}
