// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/generate/generate.proto

package generatepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SectionIds    []uint64               `protobuf:"varint,2,rep,packed,name=section_ids,json=sectionIds,proto3" json:"section_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTestRequest) Reset() {
	*x = GenerateTestRequest{}
	mi := &file_proto_generate_generate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTestRequest) ProtoMessage() {}

func (x *GenerateTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_generate_generate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTestRequest.ProtoReflect.Descriptor instead.
func (*GenerateTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_generate_generate_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateTestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateTestRequest) GetSectionIds() []uint64 {
	if x != nil {
		return x.SectionIds
	}
	return nil
}

type GenerateTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTestResponse) Reset() {
	*x = GenerateTestResponse{}
	mi := &file_proto_generate_generate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTestResponse) ProtoMessage() {}

func (x *GenerateTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_generate_generate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTestResponse.ProtoReflect.Descriptor instead.
func (*GenerateTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_generate_generate_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateTestResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type GetTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestRequest) Reset() {
	*x = GetTestRequest{}
	mi := &file_proto_generate_generate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestRequest) ProtoMessage() {}

func (x *GetTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_generate_generate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestRequest.ProtoReflect.Descriptor instead.
func (*GetTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_generate_generate_proto_rawDescGZIP(), []int{2}
}

func (x *GetTestRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestJson      string                 `protobuf:"bytes,1,opt,name=test_json,json=testJson,proto3" json:"test_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestResponse) Reset() {
	*x = GetTestResponse{}
	mi := &file_proto_generate_generate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestResponse) ProtoMessage() {}

func (x *GetTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_generate_generate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestResponse.ProtoReflect.Descriptor instead.
func (*GetTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_generate_generate_proto_rawDescGZIP(), []int{3}
}

func (x *GetTestResponse) GetTestJson() string {
	if x != nil {
		return x.TestJson
	}
	return ""
}

var File_proto_generate_generate_proto protoreflect.FileDescriptor

const file_proto_generate_generate_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/generate/generate.proto\x12\vtestservice\"J\n" +
	"\x13GenerateTestRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vsection_ids\x18\x02 \x03(\x04R\n" +
	"sectionIds\"*\n" +
	"\x14GenerateTestResponse\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\"\"\n" +
	"\x0eGetTestRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\".\n" +
	"\x0fGetTestResponse\x12\x1b\n" +
	"\ttest_json\x18\x01 \x01(\tR\btestJson2\xa8\x01\n" +
	"\vTestService\x12S\n" +
	"\fGenerateTest\x12 .testservice.GenerateTestRequest\x1a!.testservice.GenerateTestResponse\x12D\n" +
	"\aGetTest\x12\x1b.testservice.GetTestRequest\x1a\x1c.testservice.GetTestResponseB?Z=github.com/khbdev/proto-online-test/proto/generate;generatepbb\x06proto3"

var (
	file_proto_generate_generate_proto_rawDescOnce sync.Once
	file_proto_generate_generate_proto_rawDescData []byte
)

func file_proto_generate_generate_proto_rawDescGZIP() []byte {
	file_proto_generate_generate_proto_rawDescOnce.Do(func() {
		file_proto_generate_generate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_generate_generate_proto_rawDesc), len(file_proto_generate_generate_proto_rawDesc)))
	})
	return file_proto_generate_generate_proto_rawDescData
}

var file_proto_generate_generate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_generate_generate_proto_goTypes = []any{
	(*GenerateTestRequest)(nil),  // 0: testservice.GenerateTestRequest
	(*GenerateTestResponse)(nil), // 1: testservice.GenerateTestResponse
	(*GetTestRequest)(nil),       // 2: testservice.GetTestRequest
	(*GetTestResponse)(nil),      // 3: testservice.GetTestResponse
}
var file_proto_generate_generate_proto_depIdxs = []int32{
	0, // 0: testservice.TestService.GenerateTest:input_type -> testservice.GenerateTestRequest
	2, // 1: testservice.TestService.GetTest:input_type -> testservice.GetTestRequest
	1, // 2: testservice.TestService.GenerateTest:output_type -> testservice.GenerateTestResponse
	3, // 3: testservice.TestService.GetTest:output_type -> testservice.GetTestResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_generate_generate_proto_init() }
func file_proto_generate_generate_proto_init() {
	if File_proto_generate_generate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_generate_generate_proto_rawDesc), len(file_proto_generate_generate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_generate_generate_proto_goTypes,
		DependencyIndexes: file_proto_generate_generate_proto_depIdxs,
		MessageInfos:      file_proto_generate_generate_proto_msgTypes,
	}.Build()
	File_proto_generate_generate_proto = out.File
	file_proto_generate_generate_proto_goTypes = nil
	file_proto_generate_generate_proto_depIdxs = nil
}
