// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/test/test.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionId    uint64                 `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,4,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_proto_test_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{0}
}

func (x *Option) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Option) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *Option) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Option) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SectionId     uint64                 `protobuf:"varint,2,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Options       []*Option              `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_test_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{1}
}

func (x *Question) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Question) GetSectionId() uint64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Questions     []*Question            `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_proto_test_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{2}
}

func (x *Section) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Section) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Section) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

// --- SECTION ---
type SectionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionID) Reset() {
	*x = SectionID{}
	mi := &file_proto_test_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionID) ProtoMessage() {}

func (x *SectionID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionID.ProtoReflect.Descriptor instead.
func (*SectionID) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{3}
}

func (x *SectionID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionRequest) Reset() {
	*x = CreateSectionRequest{}
	mi := &file_proto_test_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionRequest) ProtoMessage() {}

func (x *CreateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionRequest.ProtoReflect.Descriptor instead.
func (*CreateSectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSectionRequest) Reset() {
	*x = UpdateSectionRequest{}
	mi := &file_proto_test_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSectionRequest) ProtoMessage() {}

func (x *UpdateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSectionRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       *Section               `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSectionResponse) Reset() {
	*x = GetSectionResponse{}
	mi := &file_proto_test_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSectionResponse) ProtoMessage() {}

func (x *GetSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSectionResponse.ProtoReflect.Descriptor instead.
func (*GetSectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{6}
}

func (x *GetSectionResponse) GetSection() *Section {
	if x != nil {
		return x.Section
	}
	return nil
}

type GetAllSectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*Section             `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSectionsResponse) Reset() {
	*x = GetAllSectionsResponse{}
	mi := &file_proto_test_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSectionsResponse) ProtoMessage() {}

func (x *GetAllSectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSectionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllSectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllSectionsResponse) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

// --- QUESTION ---
type QuestionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionID) Reset() {
	*x = QuestionID{}
	mi := &file_proto_test_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionID) ProtoMessage() {}

func (x *QuestionID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionID.ProtoReflect.Descriptor instead.
func (*QuestionID) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{8}
}

func (x *QuestionID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     uint64                 `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_proto_test_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{9}
}

func (x *CreateQuestionRequest) GetSectionId() uint64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *CreateQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SectionId     uint64                 `protobuf:"varint,2,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_proto_test_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateQuestionRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateQuestionRequest) GetSectionId() uint64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *UpdateQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionResponse) Reset() {
	*x = GetQuestionResponse{}
	mi := &file_proto_test_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionResponse) ProtoMessage() {}

func (x *GetQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{11}
}

func (x *GetQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type GetAllQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllQuestionsResponse) Reset() {
	*x = GetAllQuestionsResponse{}
	mi := &file_proto_test_test_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQuestionsResponse) ProtoMessage() {}

func (x *GetAllQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

// --- OPTION ---
type OptionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionID) Reset() {
	*x = OptionID{}
	mi := &file_proto_test_test_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionID) ProtoMessage() {}

func (x *OptionID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionID.ProtoReflect.Descriptor instead.
func (*OptionID) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{13}
}

func (x *OptionID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateOptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    uint64                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,3,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOptionRequest) Reset() {
	*x = CreateOptionRequest{}
	mi := &file_proto_test_test_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOptionRequest) ProtoMessage() {}

func (x *CreateOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOptionRequest.ProtoReflect.Descriptor instead.
func (*CreateOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{14}
}

func (x *CreateOptionRequest) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *CreateOptionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateOptionRequest) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type UpdateOptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QuestionId    uint64                 `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,4,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOptionRequest) Reset() {
	*x = UpdateOptionRequest{}
	mi := &file_proto_test_test_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOptionRequest) ProtoMessage() {}

func (x *UpdateOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateOptionRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOptionRequest) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *UpdateOptionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateOptionRequest) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type GetOptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Option        *Option                `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOptionResponse) Reset() {
	*x = GetOptionResponse{}
	mi := &file_proto_test_test_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptionResponse) ProtoMessage() {}

func (x *GetOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptionResponse.ProtoReflect.Descriptor instead.
func (*GetOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{16}
}

func (x *GetOptionResponse) GetOption() *Option {
	if x != nil {
		return x.Option
	}
	return nil
}

type GetAllOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*Option              `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOptionsResponse) Reset() {
	*x = GetAllOptionsResponse{}
	mi := &file_proto_test_test_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOptionsResponse) ProtoMessage() {}

func (x *GetAllOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllOptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllOptionsResponse) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

// --- FULL STRUCTURE ---
type GetFullSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     uint64                 `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullSectionRequest) Reset() {
	*x = GetFullSectionRequest{}
	mi := &file_proto_test_test_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullSectionRequest) ProtoMessage() {}

func (x *GetFullSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullSectionRequest.ProtoReflect.Descriptor instead.
func (*GetFullSectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{18}
}

func (x *GetFullSectionRequest) GetSectionId() uint64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

type GetFullSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       *Section               `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullSectionResponse) Reset() {
	*x = GetFullSectionResponse{}
	mi := &file_proto_test_test_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullSectionResponse) ProtoMessage() {}

func (x *GetFullSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_test_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullSectionResponse.ProtoReflect.Descriptor instead.
func (*GetFullSectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_test_proto_rawDescGZIP(), []int{19}
}

func (x *GetFullSectionResponse) GetSection() *Section {
	if x != nil {
		return x.Section
	}
	return nil
}

var File_proto_test_test_proto protoreflect.FileDescriptor

const file_proto_test_test_proto_rawDesc = "" +
	"\n" +
	"\x15proto/test/test.proto\x12\x04test\x1a\x1bgoogle/protobuf/empty.proto\"l\n" +
	"\x06Option\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x04R\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x04 \x01(\bR\tisCorrect\"u\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"section_id\x18\x02 \x01(\x04R\tsectionId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12&\n" +
	"\aoptions\x18\x04 \x03(\v2\f.test.OptionR\aoptions\"[\n" +
	"\aSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\tquestions\x18\x03 \x03(\v2\x0e.test.QuestionR\tquestions\"\x1b\n" +
	"\tSectionID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"*\n" +
	"\x14CreateSectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\":\n" +
	"\x14UpdateSectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"=\n" +
	"\x12GetSectionResponse\x12'\n" +
	"\asection\x18\x01 \x01(\v2\r.test.SectionR\asection\"C\n" +
	"\x16GetAllSectionsResponse\x12)\n" +
	"\bsections\x18\x01 \x03(\v2\r.test.SectionR\bsections\"\x1c\n" +
	"\n" +
	"QuestionID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"J\n" +
	"\x15CreateQuestionRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x04R\tsectionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"Z\n" +
	"\x15UpdateQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"section_id\x18\x02 \x01(\x04R\tsectionId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"A\n" +
	"\x13GetQuestionResponse\x12*\n" +
	"\bquestion\x18\x01 \x01(\v2\x0e.test.QuestionR\bquestion\"G\n" +
	"\x17GetAllQuestionsResponse\x12,\n" +
	"\tquestions\x18\x01 \x03(\v2\x0e.test.QuestionR\tquestions\"\x1a\n" +
	"\bOptionID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"i\n" +
	"\x13CreateOptionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x03 \x01(\bR\tisCorrect\"y\n" +
	"\x13UpdateOptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x04R\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x04 \x01(\bR\tisCorrect\"9\n" +
	"\x11GetOptionResponse\x12$\n" +
	"\x06option\x18\x01 \x01(\v2\f.test.OptionR\x06option\"?\n" +
	"\x15GetAllOptionsResponse\x12&\n" +
	"\aoptions\x18\x01 \x03(\v2\f.test.OptionR\aoptions\"6\n" +
	"\x15GetFullSectionRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x04R\tsectionId\"A\n" +
	"\x16GetFullSectionResponse\x12'\n" +
	"\asection\x18\x01 \x01(\v2\r.test.SectionR\asection2\x88\b\n" +
	"\vTestService\x12:\n" +
	"\rCreateSection\x12\x1a.test.CreateSectionRequest\x1a\r.test.Section\x12;\n" +
	"\x0eGetSectionById\x12\x0f.test.SectionID\x1a\x18.test.GetSectionResponse\x12F\n" +
	"\x0eGetAllSections\x12\x16.google.protobuf.Empty\x1a\x1c.test.GetAllSectionsResponse\x12:\n" +
	"\rUpdateSection\x12\x1a.test.UpdateSectionRequest\x1a\r.test.Section\x128\n" +
	"\rDeleteSection\x12\x0f.test.SectionID\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x0eCreateQuestion\x12\x1b.test.CreateQuestionRequest\x1a\x0e.test.Question\x12>\n" +
	"\x0fGetQuestionById\x12\x10.test.QuestionID\x1a\x19.test.GetQuestionResponse\x12H\n" +
	"\x0fGetAllQuestions\x12\x16.google.protobuf.Empty\x1a\x1d.test.GetAllQuestionsResponse\x12=\n" +
	"\x0eUpdateQuestion\x12\x1b.test.UpdateQuestionRequest\x1a\x0e.test.Question\x12:\n" +
	"\x0eDeleteQuestion\x12\x10.test.QuestionID\x1a\x16.google.protobuf.Empty\x127\n" +
	"\fCreateOption\x12\x19.test.CreateOptionRequest\x1a\f.test.Option\x128\n" +
	"\rGetOptionById\x12\x0e.test.OptionID\x1a\x17.test.GetOptionResponse\x12D\n" +
	"\rGetAllOptions\x12\x16.google.protobuf.Empty\x1a\x1b.test.GetAllOptionsResponse\x127\n" +
	"\fUpdateOption\x12\x19.test.UpdateOptionRequest\x1a\f.test.Option\x126\n" +
	"\fDeleteOption\x12\x0e.test.OptionID\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x17GetFullSectionStructure\x12\x1b.test.GetFullSectionRequest\x1a\x1c.test.GetFullSectionResponseB0Z.github.com/khbdev/grps-proto/proto/test;testpbb\x06proto3"

var (
	file_proto_test_test_proto_rawDescOnce sync.Once
	file_proto_test_test_proto_rawDescData []byte
)

func file_proto_test_test_proto_rawDescGZIP() []byte {
	file_proto_test_test_proto_rawDescOnce.Do(func() {
		file_proto_test_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_test_test_proto_rawDesc), len(file_proto_test_test_proto_rawDesc)))
	})
	return file_proto_test_test_proto_rawDescData
}

var file_proto_test_test_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_test_test_proto_goTypes = []any{
	(*Option)(nil),                  // 0: test.Option
	(*Question)(nil),                // 1: test.Question
	(*Section)(nil),                 // 2: test.Section
	(*SectionID)(nil),               // 3: test.SectionID
	(*CreateSectionRequest)(nil),    // 4: test.CreateSectionRequest
	(*UpdateSectionRequest)(nil),    // 5: test.UpdateSectionRequest
	(*GetSectionResponse)(nil),      // 6: test.GetSectionResponse
	(*GetAllSectionsResponse)(nil),  // 7: test.GetAllSectionsResponse
	(*QuestionID)(nil),              // 8: test.QuestionID
	(*CreateQuestionRequest)(nil),   // 9: test.CreateQuestionRequest
	(*UpdateQuestionRequest)(nil),   // 10: test.UpdateQuestionRequest
	(*GetQuestionResponse)(nil),     // 11: test.GetQuestionResponse
	(*GetAllQuestionsResponse)(nil), // 12: test.GetAllQuestionsResponse
	(*OptionID)(nil),                // 13: test.OptionID
	(*CreateOptionRequest)(nil),     // 14: test.CreateOptionRequest
	(*UpdateOptionRequest)(nil),     // 15: test.UpdateOptionRequest
	(*GetOptionResponse)(nil),       // 16: test.GetOptionResponse
	(*GetAllOptionsResponse)(nil),   // 17: test.GetAllOptionsResponse
	(*GetFullSectionRequest)(nil),   // 18: test.GetFullSectionRequest
	(*GetFullSectionResponse)(nil),  // 19: test.GetFullSectionResponse
	(*emptypb.Empty)(nil),           // 20: google.protobuf.Empty
}
var file_proto_test_test_proto_depIdxs = []int32{
	0,  // 0: test.Question.options:type_name -> test.Option
	1,  // 1: test.Section.questions:type_name -> test.Question
	2,  // 2: test.GetSectionResponse.section:type_name -> test.Section
	2,  // 3: test.GetAllSectionsResponse.sections:type_name -> test.Section
	1,  // 4: test.GetQuestionResponse.question:type_name -> test.Question
	1,  // 5: test.GetAllQuestionsResponse.questions:type_name -> test.Question
	0,  // 6: test.GetOptionResponse.option:type_name -> test.Option
	0,  // 7: test.GetAllOptionsResponse.options:type_name -> test.Option
	2,  // 8: test.GetFullSectionResponse.section:type_name -> test.Section
	4,  // 9: test.TestService.CreateSection:input_type -> test.CreateSectionRequest
	3,  // 10: test.TestService.GetSectionById:input_type -> test.SectionID
	20, // 11: test.TestService.GetAllSections:input_type -> google.protobuf.Empty
	5,  // 12: test.TestService.UpdateSection:input_type -> test.UpdateSectionRequest
	3,  // 13: test.TestService.DeleteSection:input_type -> test.SectionID
	9,  // 14: test.TestService.CreateQuestion:input_type -> test.CreateQuestionRequest
	8,  // 15: test.TestService.GetQuestionById:input_type -> test.QuestionID
	20, // 16: test.TestService.GetAllQuestions:input_type -> google.protobuf.Empty
	10, // 17: test.TestService.UpdateQuestion:input_type -> test.UpdateQuestionRequest
	8,  // 18: test.TestService.DeleteQuestion:input_type -> test.QuestionID
	14, // 19: test.TestService.CreateOption:input_type -> test.CreateOptionRequest
	13, // 20: test.TestService.GetOptionById:input_type -> test.OptionID
	20, // 21: test.TestService.GetAllOptions:input_type -> google.protobuf.Empty
	15, // 22: test.TestService.UpdateOption:input_type -> test.UpdateOptionRequest
	13, // 23: test.TestService.DeleteOption:input_type -> test.OptionID
	18, // 24: test.TestService.GetFullSectionStructure:input_type -> test.GetFullSectionRequest
	2,  // 25: test.TestService.CreateSection:output_type -> test.Section
	6,  // 26: test.TestService.GetSectionById:output_type -> test.GetSectionResponse
	7,  // 27: test.TestService.GetAllSections:output_type -> test.GetAllSectionsResponse
	2,  // 28: test.TestService.UpdateSection:output_type -> test.Section
	20, // 29: test.TestService.DeleteSection:output_type -> google.protobuf.Empty
	1,  // 30: test.TestService.CreateQuestion:output_type -> test.Question
	11, // 31: test.TestService.GetQuestionById:output_type -> test.GetQuestionResponse
	12, // 32: test.TestService.GetAllQuestions:output_type -> test.GetAllQuestionsResponse
	1,  // 33: test.TestService.UpdateQuestion:output_type -> test.Question
	20, // 34: test.TestService.DeleteQuestion:output_type -> google.protobuf.Empty
	0,  // 35: test.TestService.CreateOption:output_type -> test.Option
	16, // 36: test.TestService.GetOptionById:output_type -> test.GetOptionResponse
	17, // 37: test.TestService.GetAllOptions:output_type -> test.GetAllOptionsResponse
	0,  // 38: test.TestService.UpdateOption:output_type -> test.Option
	20, // 39: test.TestService.DeleteOption:output_type -> google.protobuf.Empty
	19, // 40: test.TestService.GetFullSectionStructure:output_type -> test.GetFullSectionResponse
	25, // [25:41] is the sub-list for method output_type
	9,  // [9:25] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_test_test_proto_init() }
func file_proto_test_test_proto_init() {
	if File_proto_test_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_test_test_proto_rawDesc), len(file_proto_test_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_test_test_proto_goTypes,
		DependencyIndexes: file_proto_test_test_proto_depIdxs,
		MessageInfos:      file_proto_test_test_proto_msgTypes,
	}.Build()
	File_proto_test_test_proto = out.File
	file_proto_test_test_proto_goTypes = nil
	file_proto_test_test_proto_depIdxs = nil
}
